name: release-notifications-on-pullrequest
description: A custom action to update Pull requests with comments referencing the specific release information. 
author: Shankar Venkatachalam
branding:
  icon: 'message-square'
  color: 'orange'
inputs:
  GITHUB_TOKEN:
    description: A GitHub token to execute GitHub tasks
    required: true
  enabled:
    description: Specify whether this action should run
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'  